### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by jorgenaranjo** [ScottHuangZL/yii2-google-chart#3]
When I execute composer update show me this error:

  Problem 1
    - yiisoft/yii2 2.0.6 requires bower-asset/jquery 2.1._@stable | 1.11._@stable -> no matching package found.
    - yiisoft/yii2 2.0.5 requires bower-asset/jquery 2.1._@stable | 1.11._@stable -> no matching package found.
    - yiisoft/yii2 2.0.4 requires bower-asset/jquery 2.1._@stable | 1.11._@stable -> no matching package found.
    - yiisoft/yii2 2.0.3 requires bower-asset/jquery 2.1._@stable | 1.11._@stable -> no matching package found.
    - yiisoft/yii2 2.0.2 requires bower-asset/jquery 2.1._@stable | 1.11._@stable -> no matching package found.
    - yiisoft/yii2 2.0.1 requires bower-asset/jquery 2.1._@stable | 1.11._@stable -> no matching package found.
    - yiisoft/yii2 2.0.0 requires bower-asset/jquery 2.1._@stable | 1.11._@stable -> no matching package found.
    - scotthuangzl/yii2-google-chart dev-master requires yiisoft/yii2 \* -> satisfiable by yiisoft/yii2[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6].
    - Installation request for scotthuangzl/yii2-google-chart dev-master -> satisfiable by scotthuangzl/yii2-google-chart[dev-master].

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.

Read https://getcomposer.org/doc/articles/troubleshooting.md for further common problems.

**Comment by ScottHuangZL** [comment]
Can you try below composer.json setting?  Btw, I am able to install this widget under yii2.0.6, thanks.

... ...
"minimum-stability": "stable",
    "require": {
        "php": ">=5.4.0",
        "yiisoft/yii2": ">=2.0.5",
        "yiisoft/yii2-bootstrap": "_",
        "yiisoft/yii2-swiftmailer": "_",
        "scotthuangzl/yii2-export2excel": "dev-master",
        "scotthuangzl/yii2-google-chart": "dev-master"
    },
    "require-dev": {
        "yiisoft/yii2-codeception": "_",
        "yiisoft/yii2-debug": "_",
        "yiisoft/yii2-gii": "_",
        "yiisoft/yii2-faker": "_"
    },
... ...

**Comment by ScottHuangZL** [comment]
Or, move below to "require-dev" session?

"scotthuangzl/yii2-export2excel": "dev-master",
"scotthuangzl/yii2-google-chart": "dev-master"
